install:
- gem install cocoapods -v 1.0.0 && pod repo update && pod install
osx_image: xcode7.3
language: objective-c
xcode_workspace: WordPress.xcworkspace
xcode_scheme: WordPress
xcode_sdk: iphonesimulator
cache:
- bundler
- cocoapods
notifications:
  email: true
script:
- Scripts/build.sh
env:
  global:
    secure: Sw3dwkuh9QjVYvvxcVnVN/wHGlhGjAsJjmEfGfqKMJZusdbNCU6tIZ7nmU2cVHDhozoPG4bHK62FgOmc1PhANyEQLe7eICh+G9djr0VP6Rd4/LLbv052dqpSrshwzFLDHCUvjTfEiJsTbQeuQYX2zQqFqvxV5eOnFkMoG4vK7rQ=
